from askColumnsAndRows import askColumnsAndRows
from columnSumGreaterNine import columnSumGreaterNine
from contDivisibleByThree import contDivisibleByThree
from fillMatrix import fillMatrix
from rowSort import rowSort