from ex1.functions.readRegisters import readRegisters
from ex1.functions.totalVaccinated import totalVaccinated
from ex1.functions.communeBars import communeBars
from ex1.functions.variantPorcentByCommune import variantPorcentByCommune
from ex1.functions.communeWithOmicron import communeWithOmicron
